# --- Global Simulation Settings ---
# Number of simulation runs to execute in parallel
num_simulations: 1
# Fixed random seed for reproducibility (use null or remove for random seed)
random_seed: 42
# Clock ticks per second
clock_frequency: 1000
# Scaling factor for energy values read from file (if needed)
energy_scaling_factor: 1e-2
# Default power factor used for calculating energy needs if 'power: default' is set
default_power_factor: 0.5
# Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
log_level: DEBUG

# --- Per-Protocol Settings ---
# Number of nodes for EACH protocol (e.g., 5 'ours' and 5 'baseline')
num_nodes: 5
# Duration of each simulation run in terms of nominal cycles
num_cycles: 1000

# --- Node Specific Settings ---
# Configuration for the first node instance of each protocol type
node1:
  alpha: 0.7
  capacitance: 47.0e-6 # Capacitor value (Farads)
  von: 3.0             # Turn-on voltage (Volts)
  voff: 2.4
  v_max_thr: 3.6            # Turn-off voltage (Volts)
  eadv: 48.05e-6       # Energy cost of advertisement (Joules)
  escan: 3.0e-6        # Energy cost of scanning ('ours' protocol) (Joules)
  nominal_runtime: 1000 # Nominal time slots for one charge/discharge cycle
  runtype: normal      # Behavior override for 'ours' protocol (normal, advertising, scanning)
  harvester:
    harvesting_mode: file # constant, gaussian, or file
    # Power for constant mode (Joules per tick, or 'default')
    # power: default
    # Standard deviation factor for gaussian mode (e.g., 0.1 for 10% of mean)
    # std: 0.1
    # File path for file mode
    file: "../EnergyTraces/pwr_cars.h5"

# Configuration for the second node instance of each protocol type
node2:
  alpha: 0.7
  capacitance: 47.0e-6
  von: 3.0
  voff: 2.4
  v_max_thr: 3.6
  eadv: 48.05e-6
  escan: 3.0e-6
  nominal_runtime: 1000
  runtype: normal
  harvester:
    harvesting_mode: file
    file: "../EnergyTraces/pwr_cars.h5"

# Configuration for the third node instance of each protocol type
node3:
  alpha: 0.7
  capacitance: 47.0e-6
  von: 3.0
  voff: 2.4
  v_max_thr: 3.6
  eadv: 48.05e-6
  escan: 3.0e-6
  nominal_runtime: 1000
  runtype: normal
  harvester:
    harvesting_mode: file
    file: "../EnergyTraces/pwr_cars.h5"

# Configuration for the fourth node instance of each protocol type
node4:
  alpha: 0.7
  capacitance: 47.0e-6
  von: 3.0
  voff: 2.4
  v_max_thr: 3.6
  eadv: 48.05e-6
  escan: 3.0e-6
  nominal_runtime: 1000
  runtype: normal
  harvester:
    harvesting_mode: file
    file: "../EnergyTraces/pwr_cars.h5"

# Configuration for the fifth node instance of each protocol type
node5:
  alpha: 0.7
  capacitance: 47.0e-6
  von: 3.0
  voff: 2.4
  v_max_thr: 3.6
  eadv: 48.05e-6
  escan: 3.0e-6
  nominal_runtime: 1000
  runtype: normal
  harvester:
    harvesting_mode: file
    file: "../EnergyTraces/pwr_cars.h5"
