num_nodes: 5
num_cycles: 10000
node1:
  alpha: 0.7
  capacitance: 47.0e-6
  von: 3.0
  voff: 2.4
  eadv: 48.05e-6
  escan: 3.0e-6
  nominal_runtime: 1000
  runttype: normal
  harvester:
    harvesting_mode: file
    file: "../Energy_Modelling/pwr_cars.h5"

node2:
  alpha: 0.7
  capacitance: 47.0e-6
  von: 3.0
  voff: 2.4
  eadv: 48.05e-6
  escan: 3.0e-6
  nominal_runtime: 1000
  runttype: normal
  harvester:
    harvesting_mode: file
    file: "../Energy_Modelling/pwr_cars.h5"

node3:
  alpha: 0.7
  capacitance: 47.0e-6
  von: 3.0
  voff: 2.4
  eadv: 48.05e-6
  escan: 3.0e-6
  nominal_runtime: 1000
  runttype: normal
  harvester:
    harvesting_mode: file
    file: "../Energy_Modelling/pwr_cars.h5"


node4:
  alpha: 0.7
  capacitance: 47.0e-6
  von: 3.0
  voff: 2.4
  eadv: 48.05e-6
  escan: 3.0e-6
  nominal_runtime: 1000
  runttype: normal
  harvester:
    harvesting_mode: file
    file: "../Energy_Modelling/pwr_cars.h5"

node5:
  alpha: 0.7
  capacitance: 47.0e-6
  von: 3.0
  voff: 2.4
  eadv: 48.05e-6
  escan: 3.0e-6
  nominal_runtime: 1000
  runttype: normal
  harvester:
    harvesting_mode: file
    file: "../Energy_Modelling/pwr_cars.h5"